<a href="https://colab.research.google.com/github/jiten-p14/A_Guide_to_Running_Tensorflow_Models_on_Android/blob/master/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [0]:
def activation(x):
  return 1/(1+torch.exp(-x))

In [0]:
##Generate some data
torch.manual_seed(7) #set the random seed so things are predictable

#Feature are 5 random normal variables
features = torch.randn(1, 5)
#true wieghts for our data, random variable again
weights = torch.randn_like(features)
#and a true bias term
bias = torch.randn((1, 1))

In [4]:
#solution
y = activation(torch.sum(features * weights) + bias)
print(y)

tensor([[0.1595]])


In [7]:
weights = weights.view(5, 1)
ym = activation(torch.mm(features, weights) + bias)
print(ym)

tensor([[0.1595]])


In [0]:
#example with hidden layers
##Generate some data
torch.manual_seed(7) #set the random seed so things are predictable

#Feature are 3 random normal variables
features = torch.randn((1, 3))

#define the size of each layer in our network
n_inputs = features.shape[1] #Number of input units, must watch number of input features
n_hidden = 2                 #Number of hidden layers 
n_output = 1                 #Number of output layers

#weights of inputs to hidden layers
w1 = torch.randn(n_inputs, n_hidden)
#Weights of inputs to output layers
w2 = torch.randn(n_hidden, n_output)

#and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [16]:
#solution
h = activation(torch.mm(features, w1) + B1)
output = activation(torch.mm(h, w2) + B2)
print(output)

tensor([[0.3171]])


In [19]:
#Numpy to Torch and back
a = np.random.rand(4, 3)
a

array([[0.17630986, 0.26056779, 0.66111429],
       [0.91580259, 0.52933085, 0.5894325 ],
       [0.90691957, 0.82928285, 0.97077456],
       [0.60524439, 0.92903578, 0.19563872]])

In [20]:
b = torch.from_numpy(a)
b

tensor([[0.1763, 0.2606, 0.6611],
        [0.9158, 0.5293, 0.5894],
        [0.9069, 0.8293, 0.9708],
        [0.6052, 0.9290, 0.1956]], dtype=torch.float64)

In [22]:
b.numpy()

array([[0.17630986, 0.26056779, 0.66111429],
       [0.91580259, 0.52933085, 0.5894325 ],
       [0.90691957, 0.82928285, 0.97077456],
       [0.60524439, 0.92903578, 0.19563872]])

In [23]:
#Multiply Pytorch Tensor by 2, in place
b.mul_(2)

tensor([[0.3526, 0.5211, 1.3222],
        [1.8316, 1.0587, 1.1789],
        [1.8138, 1.6586, 1.9415],
        [1.2105, 1.8581, 0.3913]], dtype=torch.float64)

In [24]:
#numpy array matches new values from Tensor
a

array([[0.35261973, 0.52113558, 1.32222859],
       [1.83160518, 1.0586617 , 1.17886499],
       [1.81383915, 1.6585657 , 1.94154912],
       [1.21048878, 1.85807156, 0.39127744]])